import 'data.dart';
import 'links.dart';

class Autogenerated {
  int? count;
  Links? links;
  List<Data>? data;

  Autogenerated({this.count, this.links, this.data});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    count = json['count'];
    links = json['links'] != null ? Links.fromJson(json['links']) : null;
    if (json['data'] != null) {
      data = <Data>[];
      json['data'].forEach((v) {
        data!.add(Data.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['count'] = count;
    if (links != null) {
      data['links'] = links!.toJson();
    }
    if (this.data != null) {
      data['data'] = this.data!.map((v) => v.toJson()).toList();
    }
    return data;
  }
}










